/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQURhZURnRGVZbWV0SmR4VjlNTWIvNzNSTk1qcEFwbUlVTGJQald4VHlubz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWnpZSmt6RkpFQ1BJV0lXUFRUTWdOTjFUeUs4SDIzS3ozM2wwOE1Gb1Bsbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrRkZDV2dwVTNqUUJBazNDNHpFWDJYN1RRbk9ZR3M2aWtUZzlvOUZXcTBrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJPWWpZTVJwNnNYVHNlU3FZUkp6Z05RMUQ0TnAyREZnQ3VEQ3YyT2V0aEdVPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlHOWhYTnNMYmw2cUwvQ1V5c1dQd3FXdlU2d0htT2JkYlRmdGJ6OW5nMmM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktGck9vTzd0S3NDcTNZR0FtMnYza3B1MkR1bUYzSm8vYkZxNmh6YU1aMXM9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVUlvdU1RYytPZVF1WW4ycU8wY3pKcHNWcExrYUF6SWpEaHFqWXBtRzBYdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTkRrMEduc3RDOE9wODU4ODlWcUc1K2FlRThBcGNST01uMTN3aXhWaW1uVT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InQyL1hKQTJvVU9iYXdCQUJEbExFUUM0Tk0wNGZra2dOQ0p3NmxIektwS2R5WnZvdkdOeVJoWTdPeVVSYTA4eFRDc1RtRFcwUmlTVkJQTHRZQ2RtaGd3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MzUsImFkdlNlY3JldEtleSI6IkNJK3NiVGFneHh2aTNLcUNSYzd3YVV4K0t3T0YwUWNhanRndHdqWEFwN1E9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzQzMjA5MDg3QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjE1MEU4MEM0RTYxMDAwNkFDODAyQTAwQjU3MUExRUUzIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzE3NTQ5Mzd9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6Ink3b2lod2lVUW1LWmpIQXE4dHZqWEEiLCJwaG9uZUlkIjoiODUzYjI0NDgtOTM1MS00MzZhLTliZTgtODUyMTk0MDEzYzZlIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFsNGlZNHdCMGdmMEhNUllTL3Z5cDY3SWFVND0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJXbFdvbkY2eWJtcGwrc0VHWXUyQkticUlpOXc9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiUjZKOEpBQU4iLCJtZSI6eyJpZCI6IjI1NDc0MzIwOTA4NzozNUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDS08vN3N3RUVLajM0YmtHR0FNZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiaHhVcE9yeTZJd1ZVNnBwTXltYU1CVzZBeCtXekdEMEJKZ0hXTWZ5TWtDST0iLCJhY2NvdW50U2lnbmF0dXJlIjoiYmw3dDY1TGwvTTQzK2N2dnNmU0hCU3ZTNG1hWHB1RDAwclBoeVdOblJiT05ORkVuNHlIR0lXZlB2aGpxaXJKWWtYcjNtbmdEcGQwcnoyODZHNmhNRGc9PSIsImRldmljZVNpZ25hdHVyZSI6Ikd0YjVtSXF6TUdJWE9XakRSM3EwOG9mR1lSMlNJWWgxZTg5blZlTnhvZDQwN2I2dWRRamV6R2k3bllOY3NZeG5MRHBUS0pMUEJPcXlrcmpxelFZbGp3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzQzMjA5MDg3OjM1QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlljVktUcTh1aU1GVk9xYVRNcG1qQVZ1Z01mbHN4ZzlBU1lCMWpIOGpKQWkifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzE3NTQ5MzMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQ2l1In0=';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "263";
const author = process.env.STICKER_AUTHOR || 'Akio';
const packname = process.env.PACKNAME || 'akio';
const dev = process.env.DEV || '263714757857';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || '𝙰𝙺𝙸𝙾-𝙼𝙳';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
